"""`aef init` — scaffold a brand-new agent directory from scratch, as
opposed to `aef adopt`, which retrofits an existing repo's current code.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

_GRAPH_TEMPLATE = '''"""Starter graph for the "{agent_name}" agent, generated by `aef init`."""

from __future__ import annotations

from aef.kernel import END, Context, Graph, Node, Route, Services
from aef.state import AEFState, StateDelta


def hello_node(state: AEFState, ctx: Context, services: Services) -> tuple[StateDelta, Route]:
    return StateDelta(working_memory={{"greeted": True}}), END


def build_graph() -> Graph:
    node = Node(id="hello", version="0.1.0", fn=hello_node, deterministic=True)
    return Graph(
        id="{agent_name}", version="0.1.0", nodes={{"hello": node}}, edges=[], entry_node="hello"
    )
'''


def _render_config(agent_name: str) -> str:
    return f"""extends: _base

model_provider:
  impl: anthropic
  model: claude-sonnet
  fallback: []

memory:
  impl: in_memory

evaluator:
  suites: []

tools:
  allow: []

policies:
  require_hitl_above_risk: 0.0
  forbid: []

objectives: "TODO: describe {agent_name}'s objective."

evolution:
  enabled: false
"""


@dataclass(frozen=True)
class InitResult:
    agent_name: str
    agent_dir: Path
    written_files: list[Path] = field(default_factory=list)
    skipped_files: list[Path] = field(default_factory=list)


def run_init(agent_name: str, base_dir: Path) -> InitResult:
    agent_dir = base_dir.resolve() / "agents" / agent_name
    agent_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    skipped: list[Path] = []

    def _write_if_absent(path: Path, content: str) -> None:
        if path.exists():
            skipped.append(path)
            return
        path.write_text(content)
        written.append(path)

    _write_if_absent(agent_dir / "__init__.py", "")
    _write_if_absent(agent_dir / "aef.yaml", _render_config(agent_name))
    _write_if_absent(agent_dir / "graph.py", _GRAPH_TEMPLATE.format(agent_name=agent_name))

    return InitResult(
        agent_name=agent_name, agent_dir=agent_dir, written_files=written, skipped_files=skipped
    )
